site_name: ONC Health IT Certification Program API Resource Guide
nav:
  - Home: index.md
  - About: about.md
  - HL7 FHIR API criterion - (g)(10): g10-criterion.md
  - HL7 C-CDA API criterion - (g)(9): g9-criterion.md
  - Non-standarized data request API criterion - (g)(8): g8-criterion.md
  - Non-standardized patient selection API criterion - (g)(7): g7-criterion.md
  - API Conditions and Maintenance of Certification requirements at ยง 170.404: 404-conditions-maintenance.md
  - HealthIT.gov Drupal API: healthit-drupal-api.md
theme:
  name: material
  scheme: default
  palette:
    primary: blue
    accemt: yellow
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
  favicon: images/logo.png
  logo: images/logo.png
extra:
  version:
    provider: mike
markdown_extensions:
  - abbr
  - pymdownx.snippets
  - pymdownx.details
  - admonition
  - pymdownx.superfences